on:
  push:
#    branches:
#      - stable
#      - next

jobs:
  native-build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        system: [ 'UCRT64', 'MINGW64' ]
    env:
      msys2_shell: ""
    steps:
      - uses: ElNounch/ramdrive@v1
      - uses: ElNounch/msys2-setup-action@v1
        id: msys2
        with:
          msystem: "${{ matrix.system }}"
          location: "R:"
          update: true
          install: "autoconf automake libtool make gcc"
      - name: Set msys2_shell env
        run: echo "msys2_shell=${{ steps.msys2.outputs.msys2_shell }}" >> $GITHUB_ENV
      - name: CI-Build
        shell: ${{ $msys2_shell }}
        run: |
          ./autogen.sh -f -o -s
          ./configure
          make && make check
