on:
  push:
#    branches:
#      - stable
#      - next

defaults:
  run:
    shell: msys2 {0}
jobs:
  native-build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        system: [ 'UCRT64', 'MINGW64' ]
    env:
      MSYSTEM: ${{ matrix.system }}
    steps:
      - uses: actions/checkout@v3
      - uses: ElNounch/ramdrive@v1
      - name: msys2 - download
        shell: powershell
        run: |
          Start-BitsTransfer "https://repo.msys2.org/distrib/msys2-x86_64-latest.sfx.exe" "R:\msys2-x86_64-latest.sfx.exe"
      - name: msys2 - unzip & first launch
        shell: cmd
        run: |
          @echo off
          "R:\msys2-x86_64-latest.sfx.exe" -y -oR:\
          del "R:\msys2-x86_64-latest.sfx.exe"
          "R:\msys64\msys2_shell.cmd" -no-start
          echo "R:\msys64\bin" >> $GITHUB_PATH
          echo "R:\msys64\usr\bin" >> $GITHUB_PATH
      - name: msys2 - update base
        shell: cmd
        run: |
          @echo off
          :Loop
          "R:\msys64\msys2_shell.cmd" "-no-start -c ""pacman -Sy && pacman --needed -S bash pacman pacman-mirrors msys2-runtime"""
          if ERRORLEVEL 1 GoTo Loop
      - name: msys2 update package database
        run: pacman -Sy
      - name: msys2 - update base
        run: pacman --needed -S bash pacman pacman-mirrors msys2-runtime
      - name: msys2 - install required packages
        run: pacman -S --needed gcc
