on:
  push:
#    branches:
#      - stable
#      - next

jobs:
  native-build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        system: [ 'UCRT64', 'MINGW64' ]
    env:
      MSYSTEM: ${{ matrix.system }}
    steps:
      - uses: actions/checkout@v3
      - uses: ElNounch/ramdrive@main
      - shell: powershell
        run: |
            Set-Location "R:\"
            Start-BitsTransfer "https://repo.msys2.org/distrib/msys2-x86_64-latest.sfx.exe" "msys2-x86_64-latest.sfx.exe"
            & "msys2-x86_64-latest.sfx.exe" -y 
            Remove-Item "msys2-x86_64-latest.sfx.exe"
            $LASTEXITCODE=-1
            while ($LASTEXITCODE -ne 0) { & "R:\msys64\msys2_shell.cmd" "-no-start" "-c 'true'" }
