on:
  push

jobs:
  native-build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        system: [ 'UCRT64', 'MINGW64' ]
    defaults:
      run:
        shell: "msysgw64.cmd -f'{0}'"
    steps:
      - uses: ElNounch/ramdrive@v1
      - uses: ElNounch/msys2-setup-action@v1
        id: msys2
        with:
          msystem: ${{ matrix.system }}
          location: "R:"
          update: true
          install: "autoconf automake libtool make gcc"
      - name: CI-Build
        shell: ${{ steps.msys2.output.msys2_shell }} -f {0}
        run: |
          ./autogen.sh -f -o -s
          ./configure
          make && make check
