on:
  push

jobs:
  native-build-windows:
    runs-on: 'windows-latest'
    strategy:
      fail-fast: false
      matrix:
        system: [ 'UCRT64', 'MINGW64', 'MINGW32', 'CLANG32', 'CLANG64' ]
    defaults:
      run:
        shell: "msys2 -f {0}"
    steps:
      - uses: 'ElNounch/msys2-setup-action@main'
        id: 'msys2'
        with:
          msystem: "${{ matrix.system }}"
          install_generic: ''
          install_msystem: 'autotools toolchain'
      - uses: actions/checkout@v3
      - name: Generate configure
        run: |
          ./autogen.sh -f -o -s
      - name: Call configure
        run: |
          ./configure CPPFLAGS='-DDEV_MODE=1'
      - name: Make and check
        run: |
          make && make check
