on:
  push:
#    branches:
#      - stable
#      - next

jobs:
  native-build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        system: [ 'UCRT64', 'MINGW64' ]
    steps:
      - uses: ElNounch/ramdrive@v1
      - uses: ElNounch/msys2-setup-action@v1
        id: msys2-setup
        with:
          msystem: ${{ matrix.system }}
          location: "R:"
#          location: "C:\\elsewhere"
          update: true
          install: "autoconf automake libtool make gcc"
      - uses: actions/checkout@v3
      - run: echo ${{ steps.msys2-setup.outputs.msys2_shell }}
      - name: CI-Build
        shell: ${{ steps.msys2-setup.outputs.msys2_shell }}
        run: |
          ./autogen.sh -f -o -s
          ./configure
          make && make check
