on:
  push:
#    branches:
#      - stable
#      - next

jobs:
  native-build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        system: [ 'UCRT64', 'MINGW64' ]
    defaults:
      run:
        shell: "msys2_shell.cmd -c '{0}'"
    steps:
      - uses: ElNounch/ramdrive@v1
      - uses: ElNounch/msys2-setup-action@main
        with:
          msystem: ${{ matrix.system }}
          location: "R:"
          update: true
          install: autoconf
      - uses: actions/checkout@v3
      - name: CI-Build
        run: |
          ./autogen.sh -s
          ./configure
          make && make check
