on:
  push:
#    branches:
#      - stable
#      - next

jobs:
  native-build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        system: [ 'UCRT64', 'MINGW64' ]
    steps:
      - uses: ElNounch/ramdrive@v1
      - uses: ElNounch/msys2-setup-action@v1
        with:
          msystem: ${{ matrix.system }}
          location: "R:"
          update: true
          install: autoconf
      - uses: actions/checkout@v3
      - name: Add to PATH
        shell: pwsh
        run: |
          echo "R:\msys64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: CI-Build
        shell: msys2_shell.cmd {0}
        run: |
          ./autogen.sh -s
          ./configure
          make && make check
