on:
  push:
#    branches:
#      - stable
#      - next

jobs:
  native-build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        system: [ 'UCRT64', 'MINGW64' ]
    defaults:
      run:
        shell: msys2_shell.cmd -f '{0}'
    steps:
#      - uses: ElNounch/ramdrive@v1
    - name: "Creating ramdisk"
      shell: powershell
      run: |
        Start-BitsTransfer "http://static.ltr-data.se/files/imdiskinst.exe" "$($env:TEMP)\imdiskinst.exe"
        Start-Process -Wait "$($env:TEMP)\imdiskinst.exe"
        Start-Process -Wait "imdisk" -ArgumentList "-a -s 3G -m R: -p ""/fs:ntfs /q /y"""
        Remove-Item "$($env:TEMP)\imdiskinst.exe"
    - uses: ElNounch/msys2-setup-action@v1
        with:
          msystem: ${{ matrix.system }}
#          location: "R:"
          location: "C:\\elsewhere"
          update: true
          install: autoconf
      - uses: actions/checkout@v3
      - name: CI-Build
        run: |
          ./autogen.sh -s
          ./configure
          make && make check
