on:
  push:
#    branches:
#      - stable
#      - next

jobs:
  native-build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: $false
      matrix:
        system: [ 'UCRT64', 'MINGW64' ]
    env:
      MSYSTEM: ${{ matrix.system }}
    steps:
      - uses: actions/checkout@v3
      - uses: ElNounch/ramdrive@v1
      - name: msys2 - unzip
        shell: powershell
        run: |
          Start-BitsTransfer "https://repo.msys2.org/distrib/msys2-x86_64-latest.sfx.exe" "R:\msys2-x86_64-latest.sfx.exe"
          & "R:\msys2-x86_64-latest.sfx.exe" -y -oR:\
          Remove-Item "R:\msys2-x86_64-latest.sfx.exe"
      - name: msys2 - setup
        run: R:\msys64\msys2_shell.cmd -no-start
      - name: msys2 - update base
        shell: powershell
        run: |
          $LASTEXITCODE = -1
          while ($LASTEXITCODE -ne 0) { & "R:\msys64\msys2_shell.cmd" "-no-start -c ""pacman --needed -S bash pacman pacman-mirrors msys2-runtime""" }

      - name: msys2 update package database
        shell: msys2 {0}
        run: pacman -Sy
        @echo off 
      - name: msys2 - update base
        shell: powershell
        run: |
          $LASTEXITCODE = -1
          while ($LASTEXITCODE -ne 0) { & "R:\msys64\msys2_shell.cmd" "-no-start -c ""pacman --needed -S bash pacman pacman-mirrors msys2-runtime""" }
      - name: msys2 - install required packages
        shell: msys2 {0}
        run: pacman -S --needed gcc
}
