on:
  push

jobs:
  native-build-windows:
    runs-on: 'windows-latest'
    strategy:
      fail-fast: false
      matrix:
        system: [ 'UCRT64', 'MINGW64' ]
    defaults:
      run:
        shell: "dynamic_shell_action.cmd -f {0}"
    steps:
      - name: "Ramdisk setup to R:"
        uses: 'ElNounch/ramdrive@v1'
        with:
          drive: 'R'
          size: '1GB'
      - uses: 'ElNounch/msys2-setup-action@main'
        id: 'msys2'
        with:
          msystem: "${{ matrix.system }}"
          location: 'R:'
          update: true
          install: 'autotools libtool'
      - name: "Msys2 as default shell"
        shell: pwsh
        run: |
          @'
          @echo off
          set ARGS=${{ steps.msys2.outputs.msys2_shell_args }}
          :Loop
          if "%~1" == "" GoTo Done
          set ARGS=%ARGS%,'%~1'
          shift
          GoTo Loop
          :Done
          powershell -Command "& {Exit (Start-Process -NoNewWindow -Wait -FilePath ${{ steps.msys2.outputs.msys2_shell_cmd }} -ArgumentList $( %ARGS% ) -PassThru).ExitCode}"
          exit %ERRORLEVEL%
          '@>"${env:WINDIR}\dynamic_shell_action.cmd"
      - uses: actions/checkout@v3
      - name: Generate configure
        run: |
          ./autogen.sh -f -o -s
      - name: Call configure
        run: |
          ./configure CPPFLAGS='-DDEV_MODE=1'
      - name: Make and check
        run: |
          make && make check
