on:
  push:
#    branches:
#      - stable
#      - next

env:
  MSYS2_SHELL: ${{ steps.msys2.outputs.msys2_shell }}

jobs:
  native-build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        system: [ 'UCRT64', 'MINGW64' ]
    defaults:
      run:
        shell: ${{ env.MSYS2_SHELL }}
    steps:
      - uses: ElNounch/ramdrive@v1
      - uses: ElNounch/msys2-setup-action@v1
        id: msys2
        with:
          msystem: "${{ matrix.system }}"
          location: "R:"
          update: true
          install: "autoconf automake libtool make gcc"
      - name: set default shell
        run: env.MSYS2_SHELL = ${{ steps.msys2.outputs.msys2_shell }}
      - name: CI-Build
        run: |
          ./autogen.sh -f -o -s
          ./configure
          make && make check
